#!/bin/sh
#
# Author: Petter Reinholdtsen <pere@td.org.uit.no>
# Date:   2000-03-18
#
# Given a libtool lib*.la, return the dll extention used (ie. so, sl,
# dll, etc)
if test "x$1" = x; then
  echo "usage: $0 <libfile.la>"
  exit 1
fi

lafile=$1

libnames=`grep library_names= $lafile`
last=`echo $libnames | cut -d\' -f2|tr " " "\n"|tail -n 1`
dllend=`echo $last | cut -d. -f2`

echo $dllend
