update_fastlane

fastlane_version "2.14.2"

default_platform :ios

platform :ios do

  before_all do
    cocoapods
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(scheme: "SaneScanner")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    gym(scheme: "SaneScanner")
    deliver(force: true)
  end

  desc "Create snapshots"
  lane :snaps do
    snapshot
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
