default_platform(:ios)

platform :ios do
    before_all do |lane, options|
      xcversion(version: "~> 13.1")
    end

    desc "Create signing certs and provisioning profiles if needed"
    lane :signing do
        app = "me.syan.SaneScanner"
        ext = "me.syan.SaneScanner.SaneScanner-FileProvider"

        cert(team_id: "79RY8264V4", development: true)
        sigh(team_id: "79RY8264V4", app_identifier: app, platform: "ios",      development: true)
        sigh(team_id: "79RY8264V4", app_identifier: ext, platform: "ios",      development: true)
        sigh(team_id: "79RY8264V4", app_identifier: app, platform: "catalyst", development: true)

        cert(team_id: "79RY8264V4")
        sigh(team_id: "79RY8264V4", app_identifier: app, platform: "ios")
        sigh(team_id: "79RY8264V4", app_identifier: app, platform: "ios",      adhoc: true)
        sigh(team_id: "79RY8264V4", app_identifier: ext, platform: "ios")
        sigh(team_id: "79RY8264V4", app_identifier: ext, platform: "ios",      adhoc: true)
        sigh(team_id: "79RY8264V4", app_identifier: app, platform: "catalyst")

        system "rm ../*.mobileprovision"
        system "rm ../*.provisionprofile"
        system "rm ../*.cer"
        system "rm ../*.p12"
        system "rm ../*.certSigningRequest"
    end

    def promptIncrementBuild
        if UI.confirm("Do you want to increase the build number before building the apps?")
            increment_build_number
        end
    end

    desc "Push a new beta build to TestFlight"
    lane :beta do
        promptIncrementBuild
        build_app(
            workspace: "SaneScanner.xcworkspace", 
            scheme: "SaneScanner",
            output_directory: "./build",
        )
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end

    desc "Deploy a new version to the App Store"
    lane :release do
        beta
        deliver(force: true)
    end

    desc "Create snapshots"
    lane :snaps do
        snapshot
    end
end
