default_platform(:ios)

platform :ios do
    before_all do |lane, options|
      xcversion(version: "~> 10.1")
    end

    desc "Create signing certs and provisioning profiles if needed"
    lane :signing do
        cert(development: true)
        sigh(development: true)

        cert
        sigh
        sigh(adhoc: true)
    
        system "rm ../*.mobileprovision"
        system "rm ../*.cer"
        system "rm ../*.p12"
        system "rm ../*.certSigningRequest"
    end

    def promptIncrementBuild
        if UI.confirm("Do you want to increase the build number before building the apps?")
            increment_build_number
        end
    end

    desc "Push a new beta build to TestFlight"
    lane :beta do
        promptIncrementBuild
        build_app(
            workspace: "SaneScanner.xcworkspace", 
            scheme: "SaneScanner",
            output_directory: "./build",
        )
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end

    desc "Deploy a new version to the App Store"
    lane :release do
        beta
        deliver(force: true)
    end

    desc "Create snapshots"
    lane :snaps do
        snapshot
    end
end
