devices([
    "iPhone SE (1st generation)",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPad Pro (12.9-inch) (5th generation)",
    "iPad Pro (11-inch) (2nd generation)",
    "iPad Pro (12.9-inch) (2nd generation)",
    "iPad Pro (10.5-inch)",
    "iPad Pro (9.7-inch)",
])

languages([
    "en-US",
    "fr-FR",
])

scheme "SaneScanner"

output_directory "./fastlane/screenshots"

clear_previous_screenshots true
skip_open_summary true
clean false
stop_after_first_error true

workspace "./SaneScanner.xcworkspace"

reinstall_app true
app_identifier "me.syan.SaneScanner"

concurrent_simulators false
localize_simulator true
