# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Pro",
  "iPad Pro Fat",
  "Apple TV 1080p"
])

languages([
  "en-US",
  "fr-FR",
])

# The name of the scheme which contains the UI Tests
scheme "SaneScanner"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true

workspace "./SaneScanner.xcworkspace"

