#!/bin/sh

DEVCLASS=$1
DEVNAME=$2

case $DEVCLASS in
0)
	# generic devices
	case "$DEVNAME" in
	ugen*)
		BUSNAME=`cat /var/run/${DEVNAME}.bus`
		rm -f /var/run/${DEVNAME}.bus
		# probably our scanner
		chgrp wheel /dev/"$DEVNAME".*
		if [ x$BUSNAME != x ] ; then
			chgrp wheel /dev/"$BUSNAME"
		fi
		;;
	esac

        ;;
esac
